// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quqxznpucxmydztixryh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1cXh6bnB1Y3hteWR6dGl4cnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjc3OTcsImV4cCI6MjA3Mzc0Mzc5N30.XNL5MP4EnoRqEc07jlSDVFGDPFmBuxg98NFTQnjTdFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});